### ISSUE TITLE
Build failure with GHC 7.10.1

### ISSUE THREAD

**Issue by deepfire** [gelisam/hawk#143] opened 2015-05-24 17:05 UTC
```
[deepfire@andromedae:~/src]$ nix-store --realise /nix/store/iry0clfj76nbb5smii50clnkhhj2yp1i-haskell-haskell-awk-1.1.drv
these derivations will be built:
  /nix/store/iry0clfj76nbb5smii50clnkhhj2yp1i-haskell-haskell-awk-1.1.drv
building path(s) ‘/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1’
setupCompilerEnvironmentPhase
Build with /nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1.
unpacking sources
unpacking source archive /nix/store/ywag3ghs9l3b3m7iz1ndpn4c0q7igjxx-haskell-awk-1.1.tar.gz
source root is haskell-awk-1.1
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/haskell-awk-1.1/revision/3.cabal.
Run jailbreak-cabal to lift version restrictions on build inputs.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-haskell-haskell-awk-1.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-haskell-haskell-awk-1.1.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-haskell-haskell-awk-1.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/lib/ghc-7.10.1/haskell-awk-1.1 --ghc-option=-j1 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring haskell-awk-1.1...
Dependency HUnit -any: using HUnit-1.2.5.2
Dependency MonadCatchIO-mtl -any: using MonadCatchIO-mtl-0.3.1.0
Dependency base -any: using base-4.8.0.0
Dependency bytestring -any: using bytestring-0.10.6.0
Dependency containers -any: using containers-0.5.6.2
Dependency directory -any: using directory-1.2.2.0
Dependency doctest -any: using doctest-0.9.13
Dependency easy-file -any: using easy-file-0.2.1
Dependency exceptions -any: using exceptions-0.8.0.2
Dependency filepath -any: using filepath-1.4.0.0
Dependency haskell-awk -any: using haskell-awk-1.1
Dependency haskell-src-exts -any: using haskell-src-exts-1.16.0.1
Dependency hint -any: using hint-0.4.2.3
Dependency hspec -any: using hspec-2.1.7
Dependency mtl -any: using mtl-2.2.1
Dependency network -any: using network-2.6.1.0
Dependency process -any: using process-1.2.3.0
Dependency stringsearch -any: using stringsearch-0.3.6.6
Dependency temporary -any: using temporary-1.2.0.3
Dependency test-framework -any: using test-framework-0.8.1.1
Dependency test-framework-hunit -any: using test-framework-hunit-0.3.0.1
Dependency time -any: using time-1.5.0.1
Dependency transformers -any: using transformers-0.4.2.0
Using Cabal-1.22.2.0 compiled by ghc-7.10
Using compiler: ghc-7.10.1
Using install prefix:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1
Binaries installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/bin
Libraries installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/lib/ghc-7.10.1/haskell-awk-1.1
Private binaries installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/libexec
Data files installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/share/x86_64-linux-ghc-7.10.1/haskell-awk-1.1
Documentation installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/share/doc/x86_64-linux-ghc-7.10.1/haskell-awk-1.1
Configuration files installed in:
/nix/store/7y8h6y5mnwsx45rj0n6xm2v6m0awlvm6-haskell-haskell-awk-1.1/etc
No alex found
Using ar found on system at:
/nix/store/fsxbvl2vrd1ms8v9jkx9pnyzfi55qxxm-binutils-2.23.1/bin/ar
No c2hs found
Using cpphs version 1.19 found on system at:
/nix/store/h7nfp63dww2k3cdjk25hap8q0dydiks5-haskell-cpphs-1.19/bin/cpphs
Using gcc version 4.8.4 given by user at:
/nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/gcc
Using ghc version 7.10.1 found on system at:
/nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1/bin/ghc
Using ghc-pkg version 7.10.1 found on system at:
/nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.16.0 found on system at:
/nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1/bin/hpc
Using hsc2hs version 0.67 found on system at:
/nix/store/j50pk13r5jysqk20gsyjdi89qcpfii57-ghc-7.10.1/bin/hsc2hs
Using hscolour version 1.22 found on system at:
/nix/store/5iv6s4f08srj38nvjclq4mhbskz8a41l-hscolour-1.23/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/aslzqiz055b7mcppiyiq548nihzvidy2-gcc-wrapper-4.8.4/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.23 found on system at:
/nix/store/fsxbvl2vrd1ms8v9jkx9pnyzfi55qxxm-binutils-2.23.1/bin/strip
Using tar found on system at:
/nix/store/fd99fvl3paah5cnf825izxpafm3c2xpr-gnutar-1.28/bin/tar
No uhc found
building
Building haskell-awk-1.1...
Preprocessing library haskell-awk-1.1...
[1 of 4] Compiling System.Console.Hawk.Representable ( runtime/System/Console/Hawk/Representable.hs, dist/build/System/Console/Hawk/Representable.o )
[2 of 4] Compiling System.Console.Hawk.Args.Spec ( runtime/System/Console/Hawk/Args/Spec.hs, dist/build/System/Console/Hawk/Args/Spec.o )
[3 of 4] Compiling System.Console.Hawk.Runtime.Base ( runtime/System/Console/Hawk/Runtime/Base.hs, dist/build/System/Console/Hawk/Runtime/Base.o )
[4 of 4] Compiling System.Console.Hawk.Runtime ( runtime/System/Console/Hawk/Runtime.hs, dist/build/System/Console/Hawk/Runtime.o )

runtime/System/Console/Hawk/Runtime.hs:8:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
In-place registering haskell-awk-1.1...
Preprocessing executable 'hawk' for haskell-awk-1.1...
[ 1 of 29] Compiling Data.Cache       ( src/Data/Cache.hs, dist/build/hawk/hawk-tmp/Data/Cache.dyn_o )
[ 2 of 29] Compiling Control.Monad.Trans.State.Persistent ( src/Control/Monad/Trans/State/Persistent.hs, dist/build/hawk/hawk-tmp/Control/Monad/Trans/State/Persistent.dyn_o )

src/Control/Monad/Trans/State/Persistent.hs:13:1: Warning:
    The import of ‘System.FilePath’ is redundant
      except perhaps to import instances from ‘System.FilePath’
    To import instances alone, use: import System.FilePath()
[ 3 of 29] Compiling System.Console.Hawk.Context.Paths ( src/System/Console/Hawk/Context/Paths.hs, dist/build/hawk/hawk-tmp/System/Console/Hawk/Context/Paths.dyn_o )
[ 4 of 29] Compiling System.Directory.Extra ( src/System/Directory/Extra.hs, dist/build/hawk/hawk-tmp/System/Directory/Extra.dyn_o )
[ 5 of 29] Compiling Data.Monoid.Ord  ( src/Data/Monoid/Ord.hs, dist/build/hawk/hawk-tmp/Data/Monoid/Ord.dyn_o )

src/Data/Monoid/Ord.hs:30:1: Warning:
    The import of ‘Data.Monoid’ is redundant
      except perhaps to import instances from ‘Data.Monoid’
    To import instances alone, use: import Data.Monoid()
[ 6 of 29] Compiling Language.Haskell.Exts.Location ( src/Language/Haskell/Exts/Location.hs, dist/build/hawk/hawk-tmp/Language/Haskell/Exts/Location.dyn_o )

src/Language/Haskell/Exts/Location.hs:40:13:
    Constructor ‘InstDecl’ should have 7 arguments, but has been given 5
    In the pattern: InstDecl loc _ _ _ _
    In an equation for ‘location’:
        location (InstDecl loc _ _ _ _) = Just loc
    In the instance declaration for ‘Location Decl’
builder for ‘/nix/store/iry0clfj76nbb5smii50clnkhhj2yp1i-haskell-haskell-awk-1.1.drv’ failed with exit code 1
```

**Comment by gelisam** [comment] 2015-05-31 20:44
This doesn't seem to have anything to do with ghc 7.10.1, but thanks for picking that title anyway, because it turns out hawk indeed has issues with ghc 7.10.1! See newly-files issue #144.

>     src/Language/Haskell/Exts/Location.hs
>         Constructor ‘InstDecl’ should have 7 arguments, but has been given 5
>         In the pattern: InstDecl loc _ _ _ _
>         In an equation for ‘location’:
>             location (InstDecl loc _ _ _ _) = Just loc
>         In the instance declaration for ‘Location Decl’

Duplicate of #136, about supporting the latest version of haskell-src-exts. You shouldn't see this though, because as a stopgap measure, I have retroactively added a version bound on Hawk's haskell-src-exts dependency, requesting the older 1.15.0.1 version in which InstDecl does have 5 arguments. I'm not familiar enough with nix to tell you how you got in this situation, but with cabal this could happen if you used `--allow-newer` or if you didn't update your package database to the latest version. You can check this by examining the [x-revision](http://www.reddit.com/r/haskell/comments/2ma5gw/package_versioning_hackage_or_cabal_issue/cm2azt5) field in your copy of haskell-awk.cabal: the latest x-revision for hawkell-awk-1.1 should be 3.

    $ tar -f ~/.cabal/packages/hackage.haskell.org/00-index.tar -x haskell-awk/1.1/haskell-awk.cabal
    $ head -n 3 haskell-awk/1.1/haskell-awk.cabal 
    Name:           haskell-awk
    Version:        1.1
    x-revision: 3

**Closed by gelisam** 2015-05-31 20:44 UTC

**Comment by gelisam** [comment] 2015-06-01 12:47
Taking a closer look at the output you pasted, I see that you are indeed using revision three...

    Replace Cabal file with edited version from http://hackage.haskell.org/package/haskell-awk-1.1/revision/3.cabal.

...but then you intentionally ignore the version bounds I have added in that revision...

    Run jailbreak-cabal to lift version restrictions on build inputs.

...which leads you to use a version of haskell-src-exts with which Hawk is known not to be compatible

    Dependency haskell-src-exts -any: using haskell-src-exts-1.16.0.1

By the way, haskell-src-exts's API often breaks from version to version, so using `haskell-src-exts -any` is really not a good idea.

**Comment by gelisam** [comment] 2015-06-01 13:11
Okay, it's not actually a duplicate of #136, it's actually a duplicate of #123, also about haskell-src-exts. In any case, #123 is closed, it's been resolved by adding an upper bound on haskell-awk-1.1 and by requiring the latest version of haskell-src-exts in HEAD. So if you insist on using `haskell-src-exts -any`, you might want to try the HEAD version instead of hawkell-awk-1.1.

**Comment by gelisam** [comment] 2015-06-01 13:13
Possibly related to #139 as well, since you're using nix.
